name: Autograding Tests
on: 
  push:
    branches:
      - main
    # paths-ignore:
    #   - '.github/**'
env:
  IMG_URL_riscv64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.1/sdcard-riscv64.img.gz # 镜像url
  IMG_URL_loongarch64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.1/sdcard-loongarch64.img.gz # 镜像url
  IMG_URL_aarch64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.1/sdcard-aarch64.img.gz # 镜像url
  IMG_URL_x86_64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.1/sdcard-x86_64.img.gz # 镜像url
  TIMEOUT: 300 # 超时时间
  SCRIPT_REPO: https://github.com/oscontent25/EvaluationScript # 脚本仓库
 
jobs:  
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, riscv64, aarch64, loongarch64]
    env:
      qemu-version: 9.2.1
    outputs:
      details: ${{ steps.autogradingbusyboxmusl.outputs.details }}
      points: ${{ steps.autogradingbusyboxmusl.outputs.points }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-01-18
          components: rust-src, llvm-tools
          targets: x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none, aarch64-unknown-none-softfloat, loongarch64-unknown-none
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-binutils
      - uses: ./.github/workflows/setup-musl
        with:
          arch: ${{ matrix.arch }}
      - uses: ./.github/workflows/setup-qemu
        with:
          qemu-version: ${{ env.qemu-version }}
      - name: Build python environment
        run: sudo apt-get install -y python3 python3-pip
      - name: build os.bin
        run: |
          touch ${{ matrix.arch }}_output.txt
          make all
      - name: run ${{ matrix.arch }} tests
        run: |
          
          wget ${IMG_URL_${{ matrix.arch }}} -O sdcard-${{ matrix.arch }}.img.gz
          gunzip sdcard-${IMG_URL_${{ matrix.arch }}}.img.gz
          qemu-system-${{ matrix.arch }} -machine virt -kernel kernel-${{ matrix.arch }} -m 2G -nographic -smp 4 -bios default -drive file=sdcard-${{ matrix.arch }}.img,if=none,format=raw,id=x0 \
                              -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0 -no-reboot -device virtio-net-device,netdev=net -netdev user,id=net \
                              -rtc base=utc \
                              -drive file=disk.img,if=none,format=raw,id=x1 -device virtio-blk-device,drive=x1,bus=virtio-mmio-bus.1 | tee ${{ matrix.arch }}_output.txt
    
  run-autograding-tests:
      runs-on: ubuntu-latest
      needs: build
      if: always()
      steps:
        - name: Download EvaluationScript
          run: |
            git clone ${{ env.SCRIPT_REPO }} .github/classroom
        - name: riscv-test
          uses: oscontent25/os-autograding@master
          id: autogradingriscv
          with:
            outputfile: riscv64_output.txt
        - name: loongarch-test
          uses: oscontent25/os-autograding@master
          id: autogradingloongarch
          with:
            outputfile: loongarch64_output.txt
        - name: aarch-test
          uses: oscontent25/os-autograding@master
          id: autogradingaarch
          with:
            outputfile: aarch64_output.txt
        - name: x86-test
          uses: oscontent25/os-autograding@master
          id: autogradingx86
          with:
            outputfile: x86_64_output.txt
        - name: Autograding Reporter
          uses: classroom-resources/autograding-grading-reporter@v1
          env:
            AUTOGRADINGRISCV_RESULTS: "${{steps.autogradingriscv.outputs.result}}"
            AUTOGRADINGLOONGARCH_RESULTS: "${{steps.autogradingloongarch.outputs.result}}"
            AUTOGRADINGAARCH_RESULTS: "${{steps.autogradingaarch.outputs.result}}"
            AUTOGRADINGX86_RESULTS: "${{steps.autogradingx86.outputs.result}}"
          with:
            runners: autogradingriscv,autogradingloongarch,autogradingaarch,autogradingx86
            token: ${{ secrets.GITHUB_TOKEN }}

